2025-08-08 17:54:21 - INFO - Starting ETL Run ID: 20250808_175421
2025-08-08 17:54:21 - INFO - ETL Run 20250808_175421 completed ï¿½ 0 file(s) processed
2025-08-08 17:55:22 - INFO - Starting ETL Run ID: 20250808_175522
2025-08-08 17:55:22 - INFO - Processing file: Monthly Data BHS Jul'25.xlsx
2025-08-08 17:55:23 - INFO - Found sheets: ['Visits', "Charges Jul'25", "Payment Jul'25", "Pending AR jul'25", "Adjustment Jul'25"]
2025-08-08 17:55:45 - INFO - CSV saved: C:\Users\MayankSharma\Project2\ETTTLLL\output\monthly_data_bhs_jul'25_clean.csv
2025-08-08 17:55:48 - INFO - Data inserted into table: claims_clean_monthly_data_bhs_jul'25 in C:\Users\MayankSharma\Project2\ETTTLLL\etl_kpis.db
2025-08-08 17:55:48 - INFO - Moved processed file to archive: Monthly Data BHS Jul'25.xlsx
2025-08-08 17:55:48 - INFO - Processed 206,424 rows from Monthly Data BHS Jul'25.xlsx in 26.13s
2025-08-08 17:55:48 - INFO - ETL Run 20250808_175522 completed ï¿½ 1 file(s) processed
2025-08-08 18:00:12 - INFO - Starting ETL Run ID: 20250808_180012
2025-08-08 18:00:12 - INFO - ETL Run 20250808_180012 completed ï¿½ 0 file(s) processed
2025-08-08 18:00:24 - INFO - Starting ETL Run ID: 20250808_180024
2025-08-08 18:00:24 - INFO - Processing file: Monthly Data BHS Jul'25.xlsx
2025-08-08 18:00:24 - INFO - Found sheets: ['Visits', "Charges Jul'25", "Payment Jul'25", "Pending AR jul'25", "Adjustment Jul'25"]
2025-08-08 18:00:43 - INFO - Removed 138 duplicate rows.
2025-08-08 18:00:43 - ERROR - Failed to process file Monthly Data BHS Jul'25.xlsx: 'DataFrame' object has no attribute 'str'
Traceback (most recent call last):
  File "C:\Users\MayankSharma\Project2\ETTTLLL\ETL.py", line 116, in <module>
    payments = clean_dataframe(payments)
  File "C:\Users\MayankSharma\Project2\ETTTLLL\ETL.py", line 58, in clean_dataframe
    df[col] = df[col].astype(str).str.strip()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\core\generic.py", line 6318, in __getattr__
    return object.__getattribute__(self, name)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute 'str'. Did you mean: 'std'?
2025-08-08 18:00:43 - INFO - ETL Run 20250808_180024 completed ï¿½ 0 file(s) processed
2025-08-08 18:01:56 - INFO - Starting ETL Run ID: 20250808_180156
2025-08-08 18:01:56 - INFO - Processing file: Monthly Data BHS Jul'25.xlsx
2025-08-08 18:01:57 - INFO - Found sheets: ['Visits', "Charges Jul'25", "Payment Jul'25", "Pending AR jul'25", "Adjustment Jul'25"]
2025-08-08 18:02:15 - INFO - Removed 138 duplicate rows.
2025-08-08 18:02:15 - INFO - Removed 2228 duplicate rows.
2025-08-08 18:02:15 - ERROR - Failed to process file Monthly Data BHS Jul'25.xlsx: 'DataFrame' object has no attribute 'str'
Traceback (most recent call last):
  File "C:\Users\MayankSharma\Project2\ETTTLLL\ETL.py", line 103, in <module>
    payments = clean_dataframe(payments)
  File "C:\Users\MayankSharma\Project2\ETTTLLL\ETL.py", line 55, in clean_dataframe
    df[col] = df[col].astype(str).str.strip().replace({"nan": None, "": None})
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\core\generic.py", line 6318, in __getattr__
    return object.__getattribute__(self, name)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute 'str'. Did you mean: 'std'?
2025-08-08 18:02:15 - INFO - ETL Run 20250808_180156 completed ï¿½ 0 file(s) processed
2025-08-08 18:27:32 - INFO - Starting ETL Run ID: 20250808_182732
2025-08-08 18:27:32 - INFO - Processing file: Monthly Data BHS Jul'25.xlsx
2025-08-08 18:27:32 - INFO - Found sheets: ['Visits', "Charges Jul'25", "Payment Jul'25", "Pending AR jul'25", "Adjustment Jul'25"]
2025-08-08 18:27:35 - INFO - Removed 138 duplicate rows.
2025-08-08 18:27:38 - INFO - Removed 2228 duplicate rows.
2025-08-08 18:27:38 - ERROR - Failed to process Monthly Data BHS Jul'25.xlsx: 'DataFrame' object has no attribute 'str'
Traceback (most recent call last):
  File "C:\Users\MayankSharma\Project2\ETTTLLL\ETL.py", line 97, in <module>
    payments = clean_dataframe(pd.read_excel(file_path, sheet_name=payments_sheet))
  File "C:\Users\MayankSharma\Project2\ETTTLLL\ETL.py", line 54, in clean_dataframe
    .str.strip()
     ^^^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\core\generic.py", line 6318, in __getattr__
    return object.__getattribute__(self, name)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute 'str'. Did you mean: 'std'?
2025-08-08 18:27:38 - INFO - ETL Run 20250808_182732 completed ï¿½ 0 file(s) processed
2025-08-08 18:28:24 - INFO - Starting ETL Run ID: 20250808_182824
2025-08-08 18:28:24 - INFO - Processing file: Monthly Data BHS Jul'25.xlsx
2025-08-08 18:28:25 - INFO - Found sheets: ['Visits', "Charges Jul'25", "Payment Jul'25", "Pending AR jul'25", "Adjustment Jul'25"]
2025-08-08 18:28:27 - INFO - Removed 138 duplicate rows.
2025-08-08 18:28:31 - INFO - Removed 2228 duplicate rows.
2025-08-08 18:28:31 - ERROR - Failed to process Monthly Data BHS Jul'25.xlsx: 'DataFrame' object has no attribute 'str'
Traceback (most recent call last):
  File "C:\Users\MayankSharma\Project2\ETTTLLL\ETL.py", line 96, in <module>
    payments = clean_dataframe(pd.read_excel(file_path, sheet_name=payments_sheet))
  File "C:\Users\MayankSharma\Project2\ETTTLLL\ETL.py", line 53, in clean_dataframe
    df[col] = df[col].str.strip()  # remove spaces
              ^^^^^^^^^^^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\core\generic.py", line 6318, in __getattr__
    return object.__getattribute__(self, name)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute 'str'. Did you mean: 'std'?
2025-08-08 18:28:31 - INFO - ETL Run 20250808_182824 completed ï¿½ 0 file(s) processed
2025-08-08 18:29:02 - INFO - Starting ETL Run ID: 20250808_182902
2025-08-08 18:29:02 - INFO - Processing file: Monthly Data BHS Jul'25.xlsx
2025-08-08 18:29:02 - INFO - Found sheets: ['Visits', "Charges Jul'25", "Payment Jul'25", "Pending AR jul'25", "Adjustment Jul'25"]
2025-08-08 18:29:04 - INFO - Removed 138 duplicate rows.
2025-08-08 18:29:08 - INFO - Removed 2228 duplicate rows.
2025-08-08 18:29:20 - INFO - Removed 300 duplicate rows.
2025-08-08 18:29:20 - ERROR - Failed to process Monthly Data BHS Jul'25.xlsx: 'account_num'
Traceback (most recent call last):
  File "C:\Users\MayankSharma\Project2\ETTTLLL\ETL.py", line 112, in <module>
    final_df = charges.merge(payments, on="account_num", how="left")
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\core\frame.py", line 10839, in merge
    return merge(
        self,
    ...<11 lines>...
        validate=validate,
    )
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\core\reshape\merge.py", line 170, in merge
    op = _MergeOperation(
        left_df,
    ...<10 lines>...
        validate=validate,
    )
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\core\reshape\merge.py", line 794, in __init__
    ) = self._get_merge_keys()
        ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\core\reshape\merge.py", line 1298, in _get_merge_keys
    right_keys.append(right._get_label_or_level_values(rk))
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\core\generic.py", line 1911, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'account_num'
2025-08-08 18:29:20 - INFO - ETL Run 20250808_182902 completed ï¿½ 0 file(s) processed
2025-08-08 18:31:11 - INFO - Starting ETL Run ID: 20250808_183111
2025-08-08 18:31:11 - INFO - Processing file: Monthly Data BHS Jul'25.xlsx
2025-08-08 18:31:12 - INFO - Found sheets: ['Visits', "Charges Jul'25", "Payment Jul'25", "Pending AR jul'25", "Adjustment Jul'25"]
2025-08-08 18:31:14 - INFO - Removed 138 duplicate rows.
2025-08-08 18:31:18 - INFO - Removed 2228 duplicate rows.
2025-08-08 18:31:30 - INFO - Removed 300 duplicate rows.
2025-08-08 18:31:30 - ERROR - Failed to process Monthly Data BHS Jul'25.xlsx: "'account_num' column missing in charges data"
Traceback (most recent call last):
  File "C:\Users\MayankSharma\Project2\ETTTLLL\ETL.py", line 124, in <module>
    raise KeyError("'account_num' column missing in charges data")
KeyError: "'account_num' column missing in charges data"
2025-08-08 18:31:30 - INFO - ETL Run 20250808_183111 completed ï¿½ 0 file(s) processed
2025-08-08 18:32:22 - INFO - Starting ETL Run ID: 20250808_183222
2025-08-08 18:32:22 - INFO - Processing file: Monthly Data BHS Jul'25.xlsx
2025-08-08 18:32:22 - INFO - Found sheets: ['Visits', "Charges Jul'25", "Payment Jul'25", "Pending AR jul'25", "Adjustment Jul'25"]
2025-08-08 18:32:24 - INFO - Removed 138 duplicate rows.
2025-08-08 18:32:28 - WARNING - Duplicate columns found and removed: ['type']
2025-08-08 18:32:28 - INFO - Removed 2228 duplicate rows.
2025-08-08 18:32:40 - WARNING - Duplicate columns found and removed: ['type']
2025-08-08 18:32:40 - INFO - Removed 300 duplicate rows.
2025-08-08 18:32:42 - INFO - CSV saved: C:\Users\MayankSharma\Project2\ETTTLLL\output\monthly_data_bhs_jul'25_clean.csv
2025-08-08 18:32:44 - INFO - Inserted into DB: claims_clean_monthly_data_bhs_jul'25
2025-08-08 18:32:44 - INFO - Archived file: Monthly Data BHS Jul'25.xlsx
2025-08-08 18:32:44 - INFO - Processed 98,085 rows from Monthly Data BHS Jul'25.xlsx in 22.0s
2025-08-08 18:32:44 - INFO - ETL Run 20250808_183222 completed ï¿½ 1 file(s) processed
2025-08-08 18:35:19 - INFO - Starting ETL Run ID: 20250808_183519
2025-08-08 18:35:19 - INFO - ETL Run 20250808_183519 completed — 0 file(s) processed
2025-08-08 18:35:27 - INFO - Starting ETL Run ID: 20250808_183527
2025-08-08 18:35:27 - INFO - Processing file: Monthly Data BHS Jul'25.xlsx
2025-08-08 18:35:27 - INFO - Found sheets: ['Visits', "Charges Jul'25", "Payment Jul'25", "Pending AR jul'25", "Adjustment Jul'25"]
2025-08-08 18:35:29 - INFO - Removed 138 duplicate rows.
2025-08-08 18:35:33 - WARNING - Duplicate columns found and removed: ['type']
2025-08-08 18:35:33 - INFO - Removed 2228 duplicate rows.
2025-08-08 18:35:47 - WARNING - Duplicate columns found and removed: ['type']
2025-08-08 18:35:47 - INFO - Removed 300 duplicate rows.
2025-08-08 18:35:49 - INFO - CSV saved: C:\Users\MayankSharma\Project2\ETTTLLL\output\monthly_data_bhs_jul'25_clean.csv
2025-08-08 18:35:50 - INFO - Inserted into DB: claims_clean_monthly_data_bhs_jul'25
2025-08-08 18:35:50 - INFO - Archived file: Monthly Data BHS Jul'25.xlsx
2025-08-08 18:35:50 - INFO - Processed 98,085 rows from Monthly Data BHS Jul'25.xlsx in 23.74s
2025-08-08 18:35:50 - INFO - ETL Run 20250808_183527 completed — 1 file(s) processed
2025-08-08 23:57:03 - INFO - Starting ETL Run ID: 20250808_235703
2025-08-08 23:57:03 - INFO - ETL Run 20250808_235703 completed — 0 file(s) processed
2025-08-08 23:57:14 - INFO - Starting ETL Run ID: 20250808_235714
2025-08-08 23:57:14 - INFO - Processing file: Monthly Data BHS Jul'25.xlsx
2025-08-08 23:57:15 - INFO - Found sheets: ['Visits', "Charges Jul'25", "Payment Jul'25", "Pending AR jul'25", "Adjustment Jul'25"]
2025-08-08 23:57:17 - INFO - Removed 138 duplicate rows.
2025-08-08 23:57:22 - WARNING - Duplicate columns found and removed: ['type']
2025-08-08 23:57:22 - INFO - Removed 2228 duplicate rows.
2025-08-08 23:57:34 - WARNING - Duplicate columns found and removed: ['type']
2025-08-08 23:57:35 - INFO - Removed 300 duplicate rows.
2025-08-08 23:57:37 - INFO - CSV saved: C:\Users\MayankSharma\Project2\ETTTLLL\output\monthly_data_bhs_jul'25_clean.csv
2025-08-08 23:57:39 - INFO - Inserted into DB: claims_clean_monthly_data_bhs_jul'25
2025-08-08 23:57:39 - INFO - Archived file: Monthly Data BHS Jul'25.xlsx
2025-08-08 23:57:39 - INFO - Processed 98,085 rows from Monthly Data BHS Jul'25.xlsx in 25.27s
2025-08-08 23:57:39 - INFO - ETL Run 20250808_235714 completed — 1 file(s) processed
2025-08-09 00:37:46 - INFO - Starting ETL Run ID: 20250809_003746
2025-08-09 00:37:46 - INFO - Processing file: Monthly Data BHS Jul'25.xlsx
2025-08-09 00:37:47 - INFO - Found sheets: ['Visits', "Charges Jul'25", "Payment Jul'25", "Pending AR jul'25", "Adjustment Jul'25"]
2025-08-09 00:37:49 - INFO - Removed 138 duplicate rows.
2025-08-09 00:37:54 - WARNING - Duplicate columns found and removed: ['type']
2025-08-09 00:37:54 - INFO - Removed 2228 duplicate rows.
2025-08-09 00:38:09 - WARNING - Duplicate columns found and removed: ['type']
2025-08-09 00:38:09 - INFO - Removed 300 duplicate rows.
2025-08-09 00:38:11 - INFO - CSV saved: C:\Users\MayankSharma\Project2\ETTTLLL\output\monthly_data_bhs_jul'25_clean.csv
2025-08-09 00:38:13 - INFO - Inserted into DB: claims_clean_monthly_data_bhs_jul'25
2025-08-09 00:38:13 - INFO - Archived file: Monthly Data BHS Jul'25.xlsx
2025-08-09 00:38:13 - INFO - Processed 98,085 rows from Monthly Data BHS Jul'25.xlsx in 26.76s
2025-08-09 00:38:13 - INFO - ETL Run 20250809_003746 completed — 1 file(s) processed
2025-08-11 17:05:59 - INFO - Starting ETL Run ID: 20250811_170559
2025-08-11 17:05:59 - INFO - ETL Run 20250811_170559 completed — 0 file(s) processed
2025-08-11 17:06:32 - INFO - Starting ETL Run ID: 20250811_170632
2025-08-11 17:06:32 - INFO - Processing file: Monthly Data BHS Jul'25.xlsx
2025-08-11 17:06:49 - ERROR - Failed to process Monthly Data BHS Jul'25.xlsx: Passing 'suffixes' which cause duplicate columns {'Payer/Insurance_x', '  Group.1_x', 'Facility Name_x', 'Financial Class_x', 'Scope_x', 'Provider Name_x', '  Specialty_x', '  Type_x', 'Acct Type_x', '  Specialty.1_x', 'Confidential_x', '  Type.1_x'} is not allowed.
Traceback (most recent call last):
  File "C:\Users\MayankSharma\Project2\ETTTLLL\ETL.py", line 167, in <module>
    merged_df = merged_df.merge(processed_sheets["Pending AR"], on="Claim No", how="left")
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\core\frame.py", line 10839, in merge
    return merge(
        self,
    ...<11 lines>...
        validate=validate,
    )
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\core\reshape\merge.py", line 184, in merge
    return op.get_result(copy=copy)
           ~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\core\reshape\merge.py", line 888, in get_result
    result = self._reindex_and_concat(
        join_index, left_indexer, right_indexer, copy=copy
    )
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\core\reshape\merge.py", line 840, in _reindex_and_concat
    llabels, rlabels = _items_overlap_with_suffix(
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.left._info_axis, self.right._info_axis, self.suffixes
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\core\reshape\merge.py", line 2757, in _items_overlap_with_suffix
    raise MergeError(
    ...<2 lines>...
    )
pandas.errors.MergeError: Passing 'suffixes' which cause duplicate columns {'Payer/Insurance_x', '  Group.1_x', 'Facility Name_x', 'Financial Class_x', 'Scope_x', 'Provider Name_x', '  Specialty_x', '  Type_x', 'Acct Type_x', '  Specialty.1_x', 'Confidential_x', '  Type.1_x'} is not allowed.
2025-08-11 17:06:49 - INFO - ETL Run 20250811_170632 completed — 0 file(s) processed
2025-08-11 17:08:46 - INFO - Starting ETL Run ID: 20250811_170846
2025-08-11 17:08:46 - INFO - Processing file: Monthly Data BHS Jul'25.xlsx
2025-08-11 17:09:03 - ERROR - Failed to process Monthly Data BHS Jul'25.xlsx: Expected numeric dtype, got object instead.
Traceback (most recent call last):
  File "C:\Users\MayankSharma\Project2\ETTTLLL\ETL.py", line 150, in <module>
    merged_df = calculate_kpis(merged_df)
  File "C:\Users\MayankSharma\Project2\ETTTLLL\ETL.py", line 106, in calculate_kpis
    df["NCR (%)"] = (df["Paid Amount"] / collectible.replace(0, pd.NA) * 100).round(2)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\core\series.py", line 2818, in round
    raise TypeError("Expected numeric dtype, got object instead.")
TypeError: Expected numeric dtype, got object instead.
2025-08-11 17:09:03 - INFO - ETL Run 20250811_170846 completed — 0 file(s) processed
2025-08-11 17:10:04 - INFO - Starting ETL Run ID: 20250811_171004
2025-08-11 17:10:04 - INFO - Processing file: Monthly Data BHS Jul'25.xlsx
2025-08-11 17:10:21 - ERROR - Failed to process Monthly Data BHS Jul'25.xlsx: Expected numeric dtype, got object instead.
Traceback (most recent call last):
  File "C:\Users\MayankSharma\Project2\ETTTLLL\ETL.py", line 174, in <module>
    merged_df = calculate_kpis(merged_df)
  File "C:\Users\MayankSharma\Project2\ETTTLLL\ETL.py", line 120, in calculate_kpis
    df["NCR (%)"] = (df["Paid Amount"] / collectible * 100).round(2)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\core\series.py", line 2818, in round
    raise TypeError("Expected numeric dtype, got object instead.")
TypeError: Expected numeric dtype, got object instead.
2025-08-11 17:10:21 - INFO - ETL Run 20250811_171004 completed — 0 file(s) processed
2025-08-11 17:11:27 - INFO - Starting ETL Run ID: 20250811_171127
2025-08-11 17:11:27 - INFO - Processing file: Monthly Data BHS Jul'25.xlsx
2025-08-11 17:11:44 - ERROR - Failed to process Monthly Data BHS Jul'25.xlsx: Expected numeric dtype, got object instead.
Traceback (most recent call last):
  File "C:\Users\MayankSharma\Project2\ETTTLLL\ETL.py", line 175, in <module>
    merged_df = calculate_kpis(merged_df)
  File "C:\Users\MayankSharma\Project2\ETTTLLL\ETL.py", line 120, in calculate_kpis
    df["NCR (%)"] = (pd.to_numeric(df["Paid Amount"], errors="coerce") / collectible * 100).round(2)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\core\series.py", line 2818, in round
    raise TypeError("Expected numeric dtype, got object instead.")
TypeError: Expected numeric dtype, got object instead.
2025-08-11 17:11:44 - INFO - ETL Run 20250811_171127 completed — 0 file(s) processed
2025-08-11 17:13:37 - INFO - Starting ETL Run ID: 20250811_171337
2025-08-11 17:13:37 - INFO - Processing file: Monthly Data BHS Jul'25.xlsx
2025-08-11 17:13:58 - INFO - Saved KPI CSV: C:\Users\MayankSharma\Project2\ETTTLLL\output\Monthly Data BHS Jul'25_with_kpis.csv
2025-08-11 17:13:58 - ERROR - Failed to process Monthly Data BHS Jul'25.xlsx: duplicate column name: Month
Traceback (most recent call last):
  File "C:\Users\MayankSharma\Project2\ETTTLLL\ETL.py", line 179, in <module>
    merged_df.to_sql(f"claims_with_kpis_{run_id}", conn, if_exists="replace", index=False)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\core\generic.py", line 3106, in to_sql
    return sql.to_sql(
           ~~~~~~~~~~^
        self,
        ^^^^^
    ...<8 lines>...
        method=method,
        ^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\io\sql.py", line 844, in to_sql
    return pandas_sql.to_sql(
           ~~~~~~~~~~~~~~~~~^
        frame,
        ^^^^^^
    ...<9 lines>...
        **engine_kwargs,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\io\sql.py", line 2840, in to_sql
    table.create()
    ~~~~~~~~~~~~^^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\io\sql.py", line 997, in create
    self._execute_create()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\io\sql.py", line 2514, in _execute_create
    conn.execute(stmt)
    ~~~~~~~~~~~~^^^^^^
sqlite3.OperationalError: duplicate column name: Month
2025-08-11 17:13:58 - INFO - ETL Run 20250811_171337 completed — 0 file(s) processed
2025-08-11 17:24:33 - INFO - Starting ETL Run ID: 20250811_172433
2025-08-11 17:24:33 - INFO - Processing file: Monthly Data BHS Jul'25.xlsx
2025-08-11 17:24:50 - ERROR - Failed to process Monthly Data BHS Jul'25.xlsx: Expected numeric dtype, got object instead.
Traceback (most recent call last):
  File "C:\Users\MayankSharma\Project2\ETTTLLL\ETL.py", line 185, in <module>
    merged_df = calculate_kpis(merged_df)
  File "C:\Users\MayankSharma\Project2\ETTTLLL\ETL.py", line 132, in calculate_kpis
    df["NCR (%)"] = (pd.to_numeric(df["Paid Amount"], errors="coerce") / collectible * 100).round(2)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\core\series.py", line 2818, in round
    raise TypeError("Expected numeric dtype, got object instead.")
TypeError: Expected numeric dtype, got object instead.
2025-08-11 17:24:50 - INFO - ETL Run 20250811_172433 completed — 0 file(s) processed
2025-08-11 17:26:39 - INFO - Starting ETL Run ID: 20250811_172639
2025-08-11 17:26:39 - INFO - Processing file: Monthly Data BHS Jul'25.xlsx
2025-08-11 17:26:56 - ERROR - Failed to process Monthly Data BHS Jul'25.xlsx: Expected numeric dtype, got object instead.
Traceback (most recent call last):
  File "C:\Users\MayankSharma\Project2\ETTTLLL\ETL.py", line 176, in <module>
    merged_df = calculate_kpis(merged_df)
  File "C:\Users\MayankSharma\Project2\ETTTLLL\ETL.py", line 123, in calculate_kpis
    df["NCR (%)"] = (paid / collectible * 100).round(2)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\core\series.py", line 2818, in round
    raise TypeError("Expected numeric dtype, got object instead.")
TypeError: Expected numeric dtype, got object instead.
2025-08-11 17:26:56 - INFO - ETL Run 20250811_172639 completed — 0 file(s) processed
2025-08-11 17:27:52 - INFO - Starting ETL Run ID: 20250811_172752
2025-08-11 17:27:52 - INFO - Processing file: Monthly Data BHS Jul'25.xlsx
2025-08-11 17:28:09 - ERROR - Failed to process Monthly Data BHS Jul'25.xlsx: float() argument must be a string or a real number, not 'NAType'
Traceback (most recent call last):
  File "C:\Users\MayankSharma\Project2\ETTTLLL\ETL.py", line 177, in <module>
    merged_df = calculate_kpis(merged_df)
  File "C:\Users\MayankSharma\Project2\ETTTLLL\ETL.py", line 124, in calculate_kpis
    df["NCR (%)"] = (paid / collectible * 100).astype(float).round(2)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\core\generic.py", line 6662, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\core\internals\managers.py", line 430, in astype
    return self.apply(
           ~~~~~~~~~~^
        "astype",
        ^^^^^^^^^
    ...<3 lines>...
        using_cow=using_copy_on_write(),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\core\internals\managers.py", line 363, in apply
    applied = getattr(b, f)(**kwargs)
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\core\internals\blocks.py", line 784, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 237, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 182, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 133, in _astype_nansafe
    return arr.astype(dtype, copy=True)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'NAType'
2025-08-11 17:28:09 - INFO - ETL Run 20250811_172752 completed — 0 file(s) processed
2025-08-11 17:29:23 - INFO - Starting ETL Run ID: 20250811_172923
2025-08-11 17:29:23 - INFO - Processing file: Monthly Data BHS Jul'25.xlsx
2025-08-11 17:29:44 - INFO - Saved KPI CSV: C:\Users\MayankSharma\Project2\ETTTLLL\output\Monthly Data BHS Jul'25_with_kpis.csv
2025-08-11 17:29:44 - ERROR - Failed to process Monthly Data BHS Jul'25.xlsx: duplicate column name: Month
Traceback (most recent call last):
  File "C:\Users\MayankSharma\Project2\ETTTLLL\ETL.py", line 188, in <module>
    merged_df.to_sql(f"claims_with_kpis_{run_id}", conn, if_exists="replace", index=False)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\core\generic.py", line 3106, in to_sql
    return sql.to_sql(
           ~~~~~~~~~~^
        self,
        ^^^^^
    ...<8 lines>...
        method=method,
        ^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\io\sql.py", line 844, in to_sql
    return pandas_sql.to_sql(
           ~~~~~~~~~~~~~~~~~^
        frame,
        ^^^^^^
    ...<9 lines>...
        **engine_kwargs,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\io\sql.py", line 2840, in to_sql
    table.create()
    ~~~~~~~~~~~~^^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\io\sql.py", line 997, in create
    self._execute_create()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\io\sql.py", line 2514, in _execute_create
    conn.execute(stmt)
    ~~~~~~~~~~~~^^^^^^
sqlite3.OperationalError: duplicate column name: Month
2025-08-11 17:29:44 - INFO - ETL Run 20250811_172923 completed — 0 file(s) processed
2025-08-11 17:32:17 - INFO - Starting ETL Run ID: 20250811_173217
2025-08-11 17:32:17 - INFO - Processing file: Monthly Data BHS Jul'25.xlsx
2025-08-11 17:32:35 - ERROR - Failed to process Monthly Data BHS Jul'25.xlsx: Expected numeric dtype, got object instead.
Traceback (most recent call last):
  File "C:\Users\MayankSharma\Project2\ETTTLLL\ETL.py", line 186, in <module>
    merged_df = calculate_kpis(merged_df)
  File "C:\Users\MayankSharma\Project2\ETTTLLL\ETL.py", line 127, in calculate_kpis
    df["GCR (%)"] = (df["Paid Amount"] / df["Billed Amount"].replace(0, pd.NA) * 100).round(2)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\core\series.py", line 2818, in round
    raise TypeError("Expected numeric dtype, got object instead.")
TypeError: Expected numeric dtype, got object instead.
2025-08-11 17:32:35 - INFO - ETL Run 20250811_173217 completed — 0 file(s) processed
2025-08-11 17:34:11 - INFO - Starting ETL Run ID: 20250811_173411
2025-08-11 17:34:11 - INFO - Processing file: Monthly Data BHS Jul'25.xlsx
2025-08-11 17:34:32 - INFO - Saved KPI CSV: C:\Users\MayankSharma\Project2\ETTTLLL\output\Monthly Data BHS Jul'25_with_kpis.csv
2025-08-11 17:34:32 - ERROR - Failed to process Monthly Data BHS Jul'25.xlsx: duplicate column name: Month
Traceback (most recent call last):
  File "C:\Users\MayankSharma\Project2\ETTTLLL\ETL.py", line 201, in <module>
    merged_df.to_sql(f"claims_with_kpis_{run_id}", conn, if_exists="replace", index=False)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\core\generic.py", line 3106, in to_sql
    return sql.to_sql(
           ~~~~~~~~~~^
        self,
        ^^^^^
    ...<8 lines>...
        method=method,
        ^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\io\sql.py", line 844, in to_sql
    return pandas_sql.to_sql(
           ~~~~~~~~~~~~~~~~~^
        frame,
        ^^^^^^
    ...<9 lines>...
        **engine_kwargs,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\io\sql.py", line 2840, in to_sql
    table.create()
    ~~~~~~~~~~~~^^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\io\sql.py", line 997, in create
    self._execute_create()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\io\sql.py", line 2514, in _execute_create
    conn.execute(stmt)
    ~~~~~~~~~~~~^^^^^^
sqlite3.OperationalError: duplicate column name: Month
2025-08-11 17:34:32 - INFO - ETL Run 20250811_173411 completed — 0 file(s) processed
2025-08-11 17:37:23 - INFO - Starting ETL Run ID: 20250811_173723
2025-08-11 17:37:23 - INFO - Processing file: Monthly Data BHS Jul'25.xlsx
2025-08-11 17:37:23 - ERROR - Failed to process Monthly Data BHS Jul'25.xlsx: 'Paid Amount'
2025-08-11 17:37:23 - INFO - ETL Run 20250811_173723 completed — 0 file(s) processed
2025-08-11 17:39:12 - INFO - Starting ETL Run ID: 20250811_173912
2025-08-11 17:39:12 - INFO - Processing file: Monthly Data BHS Jul'25.xlsx
2025-08-11 17:39:37 - INFO - Saved KPI CSV: C:\Users\MayankSharma\Project2\ETTTLLL\output\Monthly Data BHS Jul'25_with_kpis.csv
2025-08-11 17:39:37 - ERROR - Failed to process Monthly Data BHS Jul'25.xlsx: duplicate column name: Month
Traceback (most recent call last):
  File "C:\Users\MayankSharma\Project2\ETTTLLL\ETL.py", line 201, in <module>
    merged_df.to_sql(f"claims_with_kpis_{run_id}", conn, if_exists="replace", index=False)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\core\generic.py", line 3106, in to_sql
    return sql.to_sql(
           ~~~~~~~~~~^
        self,
        ^^^^^
    ...<8 lines>...
        method=method,
        ^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\io\sql.py", line 844, in to_sql
    return pandas_sql.to_sql(
           ~~~~~~~~~~~~~~~~~^
        frame,
        ^^^^^^
    ...<9 lines>...
        **engine_kwargs,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\io\sql.py", line 2840, in to_sql
    table.create()
    ~~~~~~~~~~~~^^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\io\sql.py", line 997, in create
    self._execute_create()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\io\sql.py", line 2514, in _execute_create
    conn.execute(stmt)
    ~~~~~~~~~~~~^^^^^^
sqlite3.OperationalError: duplicate column name: Month
2025-08-11 17:39:37 - INFO - ETL Run 20250811_173912 completed — 0 file(s) processed
2025-08-11 17:40:42 - INFO - Starting ETL Run ID: 20250811_174042
2025-08-11 17:40:42 - INFO - Processing file: Monthly Data BHS Jul'25.xlsx
2025-08-11 17:41:04 - INFO - Saved KPI CSV: C:\Users\MayankSharma\Project2\ETTTLLL\output\Monthly Data BHS Jul'25_with_kpis.csv
2025-08-11 17:41:07 - ERROR - Failed to process Monthly Data BHS Jul'25.xlsx: [WinError 32] The process cannot access the file because it is being used by another process: "C:\\Users\\MayankSharma\\Project2\\ETTTLLL\\input\\Monthly Data BHS Jul'25.xlsx"
Traceback (most recent call last):
  File "C:\Users\MayankSharma\miniconda3\Lib\shutil.py", line 856, in move
    os.rename(src, real_dst)
    ~~~~~~~~~^^^^^^^^^^^^^^^
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: "C:\\Users\\MayankSharma\\Project2\\ETTTLLL\\input\\Monthly Data BHS Jul'25.xlsx" -> "C:\\Users\\MayankSharma\\Project2\\ETTTLLL\\archive\\Monthly Data BHS Jul'25.xlsx"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MayankSharma\Project2\ETTTLLL\ETL.py", line 208, in <module>
    shutil.move(file_path, os.path.join(ARCHIVE_DIR, file))
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MayankSharma\miniconda3\Lib\shutil.py", line 877, in move
    os.unlink(src)
    ~~~~~~~~~^^^^^
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: "C:\\Users\\MayankSharma\\Project2\\ETTTLLL\\input\\Monthly Data BHS Jul'25.xlsx"
2025-08-11 17:41:07 - INFO - ETL Run 20250811_174042 completed — 0 file(s) processed
2025-08-11 17:41:30 - INFO - Starting ETL Run ID: 20250811_174130
2025-08-11 17:41:30 - INFO - Processing file: Monthly Data BHS Jul'25.xlsx
2025-08-11 17:41:52 - INFO - Saved KPI CSV: C:\Users\MayankSharma\Project2\ETTTLLL\output\Monthly Data BHS Jul'25_with_kpis.csv
2025-08-11 17:41:55 - ERROR - Failed to process Monthly Data BHS Jul'25.xlsx: [WinError 32] The process cannot access the file because it is being used by another process: "C:\\Users\\MayankSharma\\Project2\\ETTTLLL\\input\\Monthly Data BHS Jul'25.xlsx"
Traceback (most recent call last):
  File "C:\Users\MayankSharma\miniconda3\Lib\shutil.py", line 856, in move
    os.rename(src, real_dst)
    ~~~~~~~~~^^^^^^^^^^^^^^^
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: "C:\\Users\\MayankSharma\\Project2\\ETTTLLL\\input\\Monthly Data BHS Jul'25.xlsx" -> "C:\\Users\\MayankSharma\\Project2\\ETTTLLL\\archive\\Monthly Data BHS Jul'25.xlsx"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MayankSharma\Project2\ETTTLLL\ETL.py", line 208, in <module>
    shutil.move(file_path, os.path.join(ARCHIVE_DIR, file))
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MayankSharma\miniconda3\Lib\shutil.py", line 877, in move
    os.unlink(src)
    ~~~~~~~~~^^^^^
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: "C:\\Users\\MayankSharma\\Project2\\ETTTLLL\\input\\Monthly Data BHS Jul'25.xlsx"
2025-08-11 17:41:55 - INFO - ETL Run 20250811_174130 completed — 0 file(s) processed
2025-08-11 17:42:43 - INFO - Starting ETL Run ID: 20250811_174243
2025-08-11 17:42:43 - INFO - Processing file: Monthly Data BHS Jul'25.xlsx
2025-08-11 17:43:01 - INFO - Columns before saving: ['Claim No', 'Confidential', 'Bill/Txn', 'Payer/Insurance', 'Scope', 'Acct Type', 'Action', 'Billed Amount', 'Provider Name', 'Facility Name', '  Specialty', '  Type', 'Responsible Provider', '  Group.1', '  Specialty.1', '  Type.1', 'MONTH', 'Financial Class', 'DOS', 'Procedure', 'Description', 'Qty', 'Paid Amount', 'Fin Class', 'Reg Class', 'Type', 'Payment Entry Date', 'Visit Loc', 'Rev Site/Perf Loc', 'Month', 'Adjustment Description', 'Adjustment Amount', 'Adjustment Entry Date', 'Age Date', 'AR Balance', 'Aging Range', 'Visit Location', 'Charge Entry Date', 'Dis Date', 'Financial Status', 'Charge Lag (days)', 'Billing Lag (days)', 'GCR (%)', 'NCR (%)', 'CCR (%)', 'AR Days', '90+ AR Days (%)', 'Denial Rate (%)']
2025-08-11 17:43:04 - INFO - Saved KPI CSV: C:\Users\MayankSharma\Project2\ETTTLLL\output\Monthly Data BHS Jul'25_with_kpis.csv
2025-08-11 17:43:04 - ERROR - Failed to process Monthly Data BHS Jul'25.xlsx: duplicate column name: Month
Traceback (most recent call last):
  File "C:\Users\MayankSharma\Project2\ETTTLLL\ETL.py", line 201, in <module>
    merged_df.to_sql(f"claims_with_kpis_{run_id}", conn, if_exists="replace", index=False)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\core\generic.py", line 3106, in to_sql
    return sql.to_sql(
           ~~~~~~~~~~^
        self,
        ^^^^^
    ...<8 lines>...
        method=method,
        ^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\io\sql.py", line 844, in to_sql
    return pandas_sql.to_sql(
           ~~~~~~~~~~~~~~~~~^
        frame,
        ^^^^^^
    ...<9 lines>...
        **engine_kwargs,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\io\sql.py", line 2840, in to_sql
    table.create()
    ~~~~~~~~~~~~^^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\io\sql.py", line 997, in create
    self._execute_create()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\io\sql.py", line 2514, in _execute_create
    conn.execute(stmt)
    ~~~~~~~~~~~~^^^^^^
sqlite3.OperationalError: duplicate column name: Month
2025-08-11 17:43:04 - INFO - ETL Run 20250811_174243 completed — 0 file(s) processed
2025-08-11 17:44:02 - INFO - Starting ETL Run ID: 20250811_174402
2025-08-11 17:44:02 - INFO - Processing file: Monthly Data BHS Jul'25.xlsx
2025-08-11 17:44:21 - INFO - Columns before saving: ['Claim No', 'Confidential', 'Bill/Txn', 'Payer/Insurance', 'Scope', 'Acct Type', 'Action', 'Billed Amount', 'Provider Name', 'Facility Name', 'Specialty', 'Type', 'Responsible Provider', 'Group.1', 'Specialty.1', 'Type.1', 'MONTH', 'Financial Class', 'DOS', 'Procedure', 'Description', 'Qty', 'Paid Amount', 'Fin Class', 'Reg Class', 'Type_1', 'Payment Entry Date', 'Visit Loc', 'Rev Site/Perf Loc', 'Month_1', 'Adjustment Description', 'Adjustment Amount', 'Adjustment Entry Date', 'Age Date', 'AR Balance', 'Aging Range', 'Visit Location', 'Charge Entry Date', 'Dis Date', 'Financial Status', 'Charge Lag (days)', 'Billing Lag (days)', 'GCR (%)', 'NCR (%)', 'CCR (%)', 'AR Days', '90+ AR Days (%)', 'Denial Rate (%)']
2025-08-11 17:44:23 - INFO - Saved KPI CSV: C:\Users\MayankSharma\Project2\ETTTLLL\output\Monthly Data BHS Jul'25_with_kpis.csv
2025-08-11 17:44:26 - ERROR - Failed to process Monthly Data BHS Jul'25.xlsx: [WinError 32] The process cannot access the file because it is being used by another process: "C:\\Users\\MayankSharma\\Project2\\ETTTLLL\\input\\Monthly Data BHS Jul'25.xlsx"
Traceback (most recent call last):
  File "C:\Users\MayankSharma\miniconda3\Lib\shutil.py", line 856, in move
    os.rename(src, real_dst)
    ~~~~~~~~~^^^^^^^^^^^^^^^
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: "C:\\Users\\MayankSharma\\Project2\\ETTTLLL\\input\\Monthly Data BHS Jul'25.xlsx" -> "C:\\Users\\MayankSharma\\Project2\\ETTTLLL\\archive\\Monthly Data BHS Jul'25.xlsx"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MayankSharma\Project2\ETTTLLL\ETL.py", line 207, in <module>
    shutil.move(file_path, os.path.join(ARCHIVE_DIR, file))
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MayankSharma\miniconda3\Lib\shutil.py", line 877, in move
    os.unlink(src)
    ~~~~~~~~~^^^^^
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: "C:\\Users\\MayankSharma\\Project2\\ETTTLLL\\input\\Monthly Data BHS Jul'25.xlsx"
2025-08-11 17:44:26 - INFO - ETL Run 20250811_174402 completed — 0 file(s) processed
2025-08-11 18:31:03 - INFO - Starting ETL Run ID: 20250811_183103
2025-08-11 18:31:03 - INFO - Processing file: Monthly Data BHS Jul'25.xlsx
2025-08-11 18:31:04 - INFO - Starting ETL Run ID: 20250811_183104
2025-08-11 18:31:04 - INFO - Processing file: Monthly Data BHS Jul'25.xlsx
2025-08-11 18:31:23 - INFO - Columns before saving: ['Claim No', 'Confidential', 'Bill/Txn', 'Payer/Insurance', 'Scope', 'Acct Type', 'Action', 'Billed Amount', 'Provider Name', 'Facility Name', '  Specialty', '  Type', 'Responsible Provider', '  Group.1', '  Specialty.1', '  Type.1', 'MONTH', 'Financial Class', 'DOS', 'Procedure', 'Description', 'Qty', 'Paid Amount', 'Fin Class', 'Reg Class', 'Type', 'Payment Entry Date', 'Visit Loc', 'Rev Site/Perf Loc', 'Month', 'Adjustment Description', 'Adjustment Amount', 'Adjustment Entry Date', 'Age Date', 'AR Balance', 'Aging Range', 'Visit Location', 'Charge Entry Date', 'Dis Date', 'Financial Status', 'Charge Lag (days)', 'Billing Lag (days)', 'GCR (%)', 'NCR (%)', 'CCR (%)', 'AR Days', '90+ AR Days (%)', 'Denial Rate (%)']
2025-08-11 18:31:26 - INFO - Saved KPI CSV: C:\Users\MayankSharma\Project2\ETTTLLL\output\Monthly Data BHS Jul'25_with_kpis.csv
2025-08-11 18:31:26 - ERROR - Failed to process Monthly Data BHS Jul'25.xlsx: duplicate column name: Month
Traceback (most recent call last):
  File "C:\Users\MayankSharma\Project2\ETTTLLL\ETL.py", line 204, in <module>
    merged_df.to_sql(f"claims_with_kpis_{run_id}", conn, if_exists="replace", index=False)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\core\generic.py", line 3106, in to_sql
    return sql.to_sql(
           ~~~~~~~~~~^
        self,
        ^^^^^
    ...<8 lines>...
        method=method,
        ^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\io\sql.py", line 844, in to_sql
    return pandas_sql.to_sql(
           ~~~~~~~~~~~~~~~~~^
        frame,
        ^^^^^^
    ...<9 lines>...
        **engine_kwargs,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\io\sql.py", line 2840, in to_sql
    table.create()
    ~~~~~~~~~~~~^^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\io\sql.py", line 997, in create
    self._execute_create()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\io\sql.py", line 2514, in _execute_create
    conn.execute(stmt)
    ~~~~~~~~~~~~^^^^^^
sqlite3.OperationalError: duplicate column name: Month
2025-08-11 18:31:26 - INFO - ETL Run 20250811_183104 completed — 0 file(s) processed
2025-08-11 18:33:45 - INFO - Starting ETL Run ID: 20250811_183345
2025-08-11 18:33:45 - INFO - Processing file: Monthly Data BHS Jul'25.xlsx
2025-08-11 18:34:03 - INFO - Columns before saving: ['Claim No', 'Confidential', 'Bill/Txn', 'Payer/Insurance', 'Scope', 'Acct Type', 'Action', 'Billed Amount', 'Provider Name', 'Facility Name', '  Specialty', '  Type', 'Responsible Provider', '  Group.1', '  Specialty.1', '  Type.1', 'MONTH', 'Financial Class', 'DOS', 'Procedure', 'Description', 'Qty', 'Paid Amount', 'Fin Class', 'Reg Class', 'Type', 'Payment Entry Date', 'Visit Loc', 'Rev Site/Perf Loc', 'Month', 'Adjustment Description', 'Adjustment Amount', 'Adjustment Entry Date', 'Age Date', 'AR Balance', 'Aging Range', 'Visit Location', 'Charge Entry Date', 'Dis Date', 'Financial Status', 'Charge Lag (days)', 'Billing Lag (days)', 'GCR (%)', 'NCR (%)', 'CCR (%)', 'AR Days', '90+ AR Days (%)', 'Denial Rate (%)']
2025-08-11 18:34:06 - INFO - Saved KPI CSV: C:\Users\MayankSharma\Project2\ETTTLLL\output\Monthly Data BHS Jul'25_with_kpis.csv
2025-08-11 18:34:06 - ERROR - Failed to process Monthly Data BHS Jul'25.xlsx: duplicate column name: Month
Traceback (most recent call last):
  File "C:\Users\MayankSharma\Project2\ETTTLLL\ETL.py", line 204, in <module>
    merged_df.to_sql(f"claims_with_kpis_{run_id}", conn, if_exists="replace", index=False)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\core\generic.py", line 3106, in to_sql
    return sql.to_sql(
           ~~~~~~~~~~^
        self,
        ^^^^^
    ...<8 lines>...
        method=method,
        ^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\io\sql.py", line 844, in to_sql
    return pandas_sql.to_sql(
           ~~~~~~~~~~~~~~~~~^
        frame,
        ^^^^^^
    ...<9 lines>...
        **engine_kwargs,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\io\sql.py", line 2840, in to_sql
    table.create()
    ~~~~~~~~~~~~^^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\io\sql.py", line 997, in create
    self._execute_create()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\MayankSharma\miniconda3\Lib\site-packages\pandas\io\sql.py", line 2514, in _execute_create
    conn.execute(stmt)
    ~~~~~~~~~~~~^^^^^^
sqlite3.OperationalError: duplicate column name: Month
2025-08-11 18:34:06 - INFO - ETL Run 20250811_183345 completed — 0 file(s) processed
2025-08-11 18:35:20 - INFO - Starting ETL Run ID: 20250811_183520
2025-08-11 18:35:20 - INFO - Processing file: Monthly Data BHS Jul'25.xlsx
2025-08-11 18:35:39 - INFO - Columns before saving: ['claim no', 'confidential', 'bill/txn', 'payer/insurance', 'scope', 'acct type', 'action', 'billed amount', 'provider name', 'facility name', 'specialty', 'type', 'responsible provider', 'group.1', 'specialty.1', 'type.1', 'month', 'financial class', 'dos', 'procedure', 'description', 'qty', 'paid amount', 'fin class', 'reg class', 'type_1', 'payment entry date', 'visit loc', 'rev site/perf loc', 'month_1', 'adjustment description', 'adjustment amount', 'adjustment entry date', 'age date', 'ar balance', 'aging range', 'visit location', 'charge entry date', 'dis date', 'financial status', 'charge lag (days)', 'billing lag (days)', 'gcr (%)', 'ncr (%)', 'ccr (%)', 'ar days', '90+ ar days (%)', 'denial rate (%)']
2025-08-11 18:35:41 - INFO - Saved KPI CSV: C:\Users\MayankSharma\Project2\ETTTLLL\output\Monthly Data BHS Jul'25_with_kpis.csv
2025-08-11 18:35:45 - INFO - Processed 206424 rows from Monthly Data BHS Jul'25.xlsx in 25.5s
2025-08-11 18:35:45 - INFO - ETL Run 20250811_183520 completed — 1 file(s) processed
2025-08-11 18:53:52 - INFO - Starting ETL Run ID: 20250811_185352
2025-08-11 18:53:52 - INFO - Processing file: Monthly Data BHS Jul'25.xlsx
2025-08-11 18:54:11 - INFO - Columns before saving: ['claim no', 'confidential', 'bill/txn', 'payer/insurance', 'scope', 'acct type', 'action', 'billed amount', 'performing provider', 'facility name', 'specialty', 'type', 'provider name', 'group.1', 'specialty.1', 'type.1', 'month', 'financial class', 'dos', 'procedure', 'description', 'qty', 'paid amount', 'fin class', 'reg class', 'type_1', 'payment entry date', 'visit loc', 'rev site/perf loc', 'month_1', 'adjustment description', 'adjustment amount', 'adjustment entry date', 'age date', 'ar balance', 'aging range', 'visit location', 'charge entry date', 'dis date', 'financial status', 'charge lag (days)', 'billing lag (days)', 'gcr (%)', 'ncr (%)', 'ccr (%)', 'ar days', '90+ ar days (%)', 'denial rate (%)']
2025-08-11 18:54:14 - INFO - Saved KPI CSV: C:\Users\MayankSharma\Project2\ETTTLLL\output\Monthly Data BHS Jul'25_with_kpis.csv
2025-08-11 18:54:18 - INFO - Processed 206424 rows from Monthly Data BHS Jul'25.xlsx in 26.33s
2025-08-11 18:54:18 - INFO - ETL Run 20250811_185352 completed — 1 file(s) processed
2025-08-11 21:47:54 - INFO - Starting ETL Run ID: 20250811_214754
2025-08-11 21:47:54 - INFO - ETL Run 20250811_214754 completed — 0 file(s) processed
2025-08-11 21:48:13 - INFO - Starting ETL Run ID: 20250811_214813
2025-08-11 21:48:13 - INFO - Processing file: Monthly Data BHS Jul'25.xlsx
2025-08-11 21:48:35 - INFO - Columns before saving: ['claim no', 'confidential', 'bill/txn', 'payer/insurance', 'scope', 'acct type', 'action', 'billed amount', 'performing provider', 'facility name', 'specialty', 'type', 'provider name', 'group.1', 'specialty.1', 'type.1', 'month', 'financial class', 'dos', 'procedure', 'description', 'qty', 'paid amount', 'fin class', 'reg class', 'type_1', 'payment entry date', 'visit loc', 'rev site/perf loc', 'month_1', 'adjustment description', 'adjustment amount', 'adjustment entry date', 'age date', 'ar balance', 'aging range', 'visit location', 'charge entry date', 'dis date', 'financial status', 'charge lag (days)', 'billing lag (days)', 'gcr (%)', 'ncr (%)', 'ccr (%)', 'ar days', '90+ ar days (%)', 'denial rate (%)']
2025-08-11 21:48:38 - INFO - Saved KPI CSV: C:\Users\MayankSharma\Project2\ETTTLLL\output\Monthly Data BHS Jul'25_with_kpis.csv
2025-08-11 21:48:43 - INFO - Processed 206424 rows from Monthly Data BHS Jul'25.xlsx in 29.96s
2025-08-11 21:48:43 - INFO - ETL Run 20250811_214813 completed — 1 file(s) processed
2025-08-12 17:55:24 - INFO - Starting ETL Run ID: 20250812_175524
2025-08-12 17:55:24 - INFO - ETL Run 20250812_175524 completed — 0 file(s) processed
2025-08-12 17:55:45 - INFO - Starting ETL Run ID: 20250812_175545
2025-08-12 17:55:45 - INFO - Processing file: Monthly Data BHS Jul'25.xlsx
2025-08-12 17:56:07 - INFO - Columns before saving: ['claim no', 'confidential', 'bill/txn', 'payer/insurance', 'scope', 'acct type', 'action', 'billed amount', 'performing provider', 'facility name', 'specialty', 'type', 'provider name', 'group.1', 'specialty.1', 'type.1', 'month', 'financial class', 'dos', 'procedure', 'description', 'qty', 'paid amount', 'fin class', 'reg class', 'type_1', 'payment entry date', 'visit loc', 'rev site/perf loc', 'month_1', 'adjustment description', 'adjustment amount', 'adjustment entry date', 'age date', 'ar balance', 'aging range', 'visit location', 'charge entry date', 'dis date', 'financial status', 'charge lag (days)', 'billing lag (days)', 'gcr (%)', 'ncr (%)', 'ccr (%)', 'ar days', '90+ ar days (%)', 'denial rate (%)']
2025-08-12 17:56:10 - INFO - Saved KPI CSV: C:\Users\MayankSharma\Project2\ETTTLLL\output\Monthly Data BHS Jul'25_with_kpis.csv
2025-08-12 17:56:14 - INFO - Processed 206424 rows from Monthly Data BHS Jul'25.xlsx in 29.47s
2025-08-12 17:56:14 - INFO - ETL Run 20250812_175545 completed — 1 file(s) processed
2025-08-12 18:22:04 - INFO - Starting ETL Run ID: 20250812_182204
2025-08-12 18:22:04 - INFO - Processing file: Monthly Data BHS Jul'25.xlsx
2025-08-12 18:22:25 - INFO - Columns before saving: ['claim no', 'confidential', 'bill/txn', 'payer/insurance', 'scope', 'acct type', 'action', 'billed amount', 'performing provider', 'facility name', 'specialty', 'type', 'provider name', 'group.1', 'specialty.1', 'type.1', 'month', 'financial class', 'dos', 'procedure', 'description', 'qty', 'paid amount', 'fin class', 'reg class', 'type_1', 'payment entry date', 'visit loc', 'rev site/perf loc', 'month_1', 'adjustment description', 'adjustment amount', 'adjustment entry date', 'age date', 'ar balance', 'aging range', 'visit location', 'charge entry date', 'dis date', 'financial status', 'charge lag (days)', 'billing lag (days)', 'gcr (%)', 'ncr (%)', 'ccr (%)', 'ar days', '90+ ar days (%)', 'denial rate (%)']
2025-08-12 18:22:27 - INFO - Saved KPI CSV: C:\Users\MayankSharma\Project2\ETTTLLL\output\Monthly Data BHS Jul'25_with_kpis.csv
2025-08-12 18:22:32 - INFO - Processed 206424 rows from Monthly Data BHS Jul'25.xlsx in 27.35s
2025-08-12 18:22:32 - INFO - ETL Run 20250812_182204 completed — 1 file(s) processed
2025-08-12 20:10:16 - INFO - Starting ETL Run ID: 20250812_201016
2025-08-12 20:10:16 - INFO - Processing file: Monthly Data BHS Jul'25.xlsx
2025-08-12 20:10:37 - INFO - Columns before saving: ['claim no', 'confidential', 'bill/txn', 'payer/insurance', 'scope', 'acct type', 'action', 'billed amount', 'performing provider', 'facility name', 'specialty', 'type', 'provider name', 'group.1', 'specialty.1', 'type.1', 'month', 'financial class', 'dos', 'procedure', 'description', 'qty', 'paid amount', 'fin class', 'reg class', 'type_1', 'payment entry date', 'visit loc', 'rev site/perf loc', 'month_1', 'adjustment description', 'adjustment amount', 'adjustment entry date', 'age date', 'ar balance', 'aging range', 'visit location', 'charge entry date', 'dis date', 'financial status', 'charge lag (days)', 'billing lag (days)', 'gcr (%)', 'ncr (%)', 'ccr (%)', 'ar days', '90+ ar days (%)', 'denial rate (%)']
2025-08-12 20:10:39 - INFO - Saved KPI CSV: C:\Users\MayankSharma\Project2\ETTTLLL\output\Monthly Data BHS Jul'25_with_kpis.csv
2025-08-12 20:10:44 - INFO - Processed 206424 rows from Monthly Data BHS Jul'25.xlsx in 27.78s
2025-08-12 20:10:44 - INFO - ETL Run 20250812_201016 completed — 1 file(s) processed
2025-08-18 11:22:21 - INFO - Starting ETL Run ID: 20250818_112221
2025-08-18 11:22:21 - INFO - Processing file: Monthly Data BHS Jul'25.xlsx
2025-08-18 11:22:21 - ERROR - Failed to process Monthly Data BHS Jul'25.xlsx: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
Traceback (most recent call last):
  File "C:\Users\jaiDevUser\Desktop\ETTTLLL\.venv\Lib\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Users\jaiDevUser\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'openpyxl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jaiDevUser\Desktop\ETTTLLL\ETL.py", line 170, in <module>
    with pd.ExcelFile(file_path) as xl:
         ~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\jaiDevUser\Desktop\ETTTLLL\.venv\Lib\site-packages\pandas\io\excel\_base.py", line 1567, in __init__
    self._reader = self._engines[engine](
                   ~~~~~~~~~~~~~~~~~~~~~^
        self._io,
        ^^^^^^^^^
        storage_options=storage_options,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        engine_kwargs=engine_kwargs,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\jaiDevUser\Desktop\ETTTLLL\.venv\Lib\site-packages\pandas\io\excel\_openpyxl.py", line 552, in __init__
    import_optional_dependency("openpyxl")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\jaiDevUser\Desktop\ETTTLLL\.venv\Lib\site-packages\pandas\compat\_optional.py", line 138, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
2025-08-18 11:22:21 - INFO - ETL Run 20250818_112221 completed — 0 file(s) processed
2025-08-18 11:23:32 - INFO - Starting ETL Run ID: 20250818_112332
2025-08-18 11:23:32 - INFO - Processing file: Monthly Data BHS Jul'25.xlsx
2025-08-18 11:24:09 - INFO - Columns before saving: ['claim no', 'confidential', 'bill/txn', 'payer/insurance', 'scope', 'acct type', 'action', 'billed amount', 'performing provider', 'facility name', 'specialty', 'type', 'provider name', 'group.1', 'specialty.1', 'type.1', 'month', 'financial class', 'dos', 'procedure', 'description', 'qty', 'paid amount', 'fin class', 'reg class', 'type_1', 'payment entry date', 'visit loc', 'rev site/perf loc', 'month_1', 'adjustment description', 'adjustment amount', 'adjustment entry date', 'age date', 'ar balance', 'aging range', 'visit location', 'charge entry date', 'dis date', 'financial status', 'charge lag (days)', 'billing lag (days)', 'gcr (%)', 'ncr (%)', 'ccr (%)', 'ar days', '90+ ar days (%)', 'denial rate (%)']
2025-08-18 11:24:15 - INFO - Saved KPI CSV: C:\Users\jaiDevUser\Desktop\ETTTLLL\output\Monthly Data BHS Jul'25_with_kpis.csv
2025-08-18 11:24:22 - INFO - Processed 206424 rows from Monthly Data BHS Jul'25.xlsx in 49.6s
2025-08-18 11:24:22 - INFO - ETL Run 20250818_112332 completed — 1 file(s) processed
